#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

VICUNA_SYSTEM_ENV_FILE="${VICUNA_SYSTEM_ENV_FILE:-/etc/vicuna/vicuna.env}"

set -a
if [[ -r "$REPO_ROOT/.envrc" ]]; then
    # shellcheck disable=SC1091
    source "$REPO_ROOT/.envrc"
fi

if [[ -r "$VICUNA_SYSTEM_ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$VICUNA_SYSTEM_ENV_FILE"
elif [[ -f "$VICUNA_SYSTEM_ENV_FILE" ]]; then
    printf '[vicuna-runtime-env] warning: %s exists but is not readable\n' "$VICUNA_SYSTEM_ENV_FILE" >&2
fi
set +a

export PATH="/usr/local/cuda-12.8/bin:$PATH"
export CUDACXX="${CUDACXX:-/usr/local/cuda-12.8/bin/nvcc}"
export LD_LIBRARY_PATH="/usr/local/cuda-12.8/lib64:${LD_LIBRARY_PATH:-}"

export VICUNA_SYSTEM_ENV_FILE
export VICUNA_REPO_ROOT="${VICUNA_REPO_ROOT:-$REPO_ROOT}"
export VICUNA_RUNTIME_SERVICE_NAME="${VICUNA_RUNTIME_SERVICE_NAME:-vicuna-runtime.service}"
export VICUNA_TELEGRAM_BRIDGE_SERVICE_NAME="${VICUNA_TELEGRAM_BRIDGE_SERVICE_NAME:-vicuna-telegram-bridge.service}"
export VICUNA_WEBGL_RENDERER_SERVICE_NAME="${VICUNA_WEBGL_RENDERER_SERVICE_NAME:-vicuna-webgl-renderer.service}"
export VICUNA_DEEPSEEK_BASE_URL="${VICUNA_DEEPSEEK_BASE_URL:-https://api.deepseek.com}"
export VICUNA_DEEPSEEK_MODEL="${VICUNA_DEEPSEEK_MODEL:-deepseek-chat}"
export VICUNA_DEEPSEEK_TIMEOUT_MS="${VICUNA_DEEPSEEK_TIMEOUT_MS:-60000}"
export TELEGRAM_BRIDGE_MODEL="${TELEGRAM_BRIDGE_MODEL:-$VICUNA_DEEPSEEK_MODEL}"
export VICUNA_OPENCLAW_TOOL_FABRIC_SECRETS_PATH="${VICUNA_OPENCLAW_TOOL_FABRIC_SECRETS_PATH:-/etc/vicuna/openclaw-tool-secrets.json}"
export VICUNA_OPENCLAW_TOOL_FABRIC_CATALOG_PATH="${VICUNA_OPENCLAW_TOOL_FABRIC_CATALOG_PATH:-/var/lib/vicuna/openclaw-catalog.json}"
export VICUNA_STATE_ROOT="${VICUNA_STATE_ROOT:-/var/lib/vicuna}"
export VICUNA_OPENCLAW_NODE_BIN="${VICUNA_OPENCLAW_NODE_BIN:-${TELEGRAM_BRIDGE_NODE_BIN:-}}"
export VICUNA_HOST_SHELL_ROOT="${VICUNA_HOST_SHELL_ROOT:-/home/vicuna/home}"
export VICUNA_HARD_MEMORY_DIR="${VICUNA_HARD_MEMORY_DIR:-$VICUNA_HOST_SHELL_ROOT/memories}"
export VICUNA_SKILLS_DIR="${VICUNA_SKILLS_DIR:-$VICUNA_HOST_SHELL_ROOT/skills}"
export VICUNA_DOCS_DIR="${VICUNA_DOCS_DIR:-$VICUNA_HOST_SHELL_ROOT/docs}"
export VICUNA_HEURISTIC_MEMORY_PATH="${VICUNA_HEURISTIC_MEMORY_PATH:-$VICUNA_HOST_SHELL_ROOT/heuristics/vicuna-heuristic-memory.json}"
export VICUNA_ONGOING_TASKS_DIR="${VICUNA_ONGOING_TASKS_DIR:-$VICUNA_STATE_ROOT/ongoing-tasks}"
export VICUNA_ONGOING_TASKS_TMPDIR="${VICUNA_ONGOING_TASKS_TMPDIR:-$VICUNA_ONGOING_TASKS_DIR/tmp}"
export VICUNA_ONGOING_TASKS_RUNNER_SCRIPT="${VICUNA_ONGOING_TASKS_RUNNER_SCRIPT:-$VICUNA_REPO_ROOT/tools/ops/run-ongoing-task-cron.sh}"
export VICUNA_ONGOING_TASKS_RUNTIME_URL="${VICUNA_ONGOING_TASKS_RUNTIME_URL:-http://127.0.0.1:${VICUNA_RUNTIME_PORT:-8080}/v1/chat/completions}"
export VICUNA_ONGOING_TASKS_RUNTIME_MODEL="${VICUNA_ONGOING_TASKS_RUNTIME_MODEL:-$VICUNA_DEEPSEEK_MODEL}"
export VICUNA_POLICY_DATASET_DIR="${VICUNA_POLICY_DATASET_DIR:-$VICUNA_STATE_ROOT/policy-datasets/nightly}"
export VICUNA_POLICY_REGISTRY_DIR="${VICUNA_POLICY_REGISTRY_DIR:-$VICUNA_STATE_ROOT/policy-registry}"
export VICUNA_POLICY_RUN_ROOT="${VICUNA_POLICY_RUN_ROOT:-$VICUNA_STATE_ROOT/policy-runs}"
export VICUNA_POLICY_MODEL_NAME="${VICUNA_POLICY_MODEL_NAME:-vicuna-governance}"
export VICUNA_POLICY_SERVER_URL="${VICUNA_POLICY_SERVER_URL:-http://127.0.0.1:${VICUNA_RUNTIME_PORT:-8080}}"
export VICUNA_POLICY_REGISTRY_HOST="${VICUNA_POLICY_REGISTRY_HOST:-127.0.0.1}"
export VICUNA_POLICY_REGISTRY_PORT="${VICUNA_POLICY_REGISTRY_PORT:-18081}"
export VICUNA_POLICY_DEFAULT_ALIAS="${VICUNA_POLICY_DEFAULT_ALIAS:-candidate}"
export VICUNA_POLICY_FALLBACK_ALIAS="${VICUNA_POLICY_FALLBACK_ALIAS:-champion}"
