#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

VICUNA_SYSTEM_ENV_FILE="${VICUNA_SYSTEM_ENV_FILE:-/etc/vicuna/vicuna.env}"

set -a
if [[ -r "$REPO_ROOT/.envrc" ]]; then
    # shellcheck disable=SC1091
    source "$REPO_ROOT/.envrc"
fi

if [[ -r "$VICUNA_SYSTEM_ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$VICUNA_SYSTEM_ENV_FILE"
elif [[ -f "$VICUNA_SYSTEM_ENV_FILE" ]]; then
    printf '[vicuna-runtime-env] warning: %s exists but is not readable\n' "$VICUNA_SYSTEM_ENV_FILE" >&2
fi
set +a

export PATH="/usr/local/cuda-12.8/bin:$PATH"
export CUDACXX="${CUDACXX:-/usr/local/cuda-12.8/bin/nvcc}"
export LD_LIBRARY_PATH="/usr/local/cuda-12.8/lib64:${LD_LIBRARY_PATH:-}"

export VICUNA_SYSTEM_ENV_FILE
export VICUNA_SERVICE_USER="${VICUNA_SERVICE_USER:-vicuna}"
export VICUNA_REPO_ROOT="${VICUNA_REPO_ROOT:-$REPO_ROOT}"
export VICUNA_LOG_ROOT="${VICUNA_LOG_ROOT:-/var/log/vicuna}"
export VICUNA_LOG_RETENTION_DAYS="${VICUNA_LOG_RETENTION_DAYS:-7}"
export VICUNA_LEGACY_OBSERVABILITY_ARCHIVE_ROOT="${VICUNA_LEGACY_OBSERVABILITY_ARCHIVE_ROOT:-${VICUNA_STATE_ROOT:-/var/lib/vicuna}/backup/legacy-observability}"
export VICUNA_RUNTIME_SERVICE_NAME="${VICUNA_RUNTIME_SERVICE_NAME:-vicuna-runtime.service}"
export VICUNA_TELEGRAM_BRIDGE_SERVICE_NAME="${VICUNA_TELEGRAM_BRIDGE_SERVICE_NAME:-vicuna-telegram-bridge.service}"
export VICUNA_WEBGL_RENDERER_SERVICE_NAME="${VICUNA_WEBGL_RENDERER_SERVICE_NAME:-vicuna-webgl-renderer.service}"
export VICUNA_POLICY_REGISTRY_SERVICE_NAME="${VICUNA_POLICY_REGISTRY_SERVICE_NAME:-vicuna-policy-registry.service}"
export VICUNA_POLICY_ROLLOUT_SERVICE_NAME="${VICUNA_POLICY_ROLLOUT_SERVICE_NAME:-vicuna-policy-rollout.service}"
export VICUNA_POLICY_ROLLOUT_TIMER_NAME="${VICUNA_POLICY_ROLLOUT_TIMER_NAME:-vicuna-policy-rollout.timer}"
export VICUNA_POLICY_NIGHTLY_SERVICE_NAME="${VICUNA_POLICY_NIGHTLY_SERVICE_NAME:-vicuna-policy-nightly.service}"
export VICUNA_POLICY_NIGHTLY_TIMER_NAME="${VICUNA_POLICY_NIGHTLY_TIMER_NAME:-vicuna-policy-nightly.timer}"
export VICUNA_DEEPSEEK_BASE_URL="${VICUNA_DEEPSEEK_BASE_URL:-https://api.deepseek.com}"
export VICUNA_DEEPSEEK_MODEL="${VICUNA_DEEPSEEK_MODEL:-deepseek-chat}"
export VICUNA_DEEPSEEK_TIMEOUT_MS="${VICUNA_DEEPSEEK_TIMEOUT_MS:-60000}"
export VICUNA_HOST_INFERENCE_MODE="${VICUNA_HOST_INFERENCE_MODE:-standard}"
export TELEGRAM_BRIDGE_REQUEST_TIMEOUT_MS="${TELEGRAM_BRIDGE_REQUEST_TIMEOUT_MS:-1800000}"
export TELEGRAM_BRIDGE_MODEL="${TELEGRAM_BRIDGE_MODEL:-$VICUNA_DEEPSEEK_MODEL}"
export VICUNA_OPENCLAW_TOOL_FABRIC_SECRETS_PATH="${VICUNA_OPENCLAW_TOOL_FABRIC_SECRETS_PATH:-/etc/vicuna/openclaw-tool-secrets.json}"
export VICUNA_OPENCLAW_TOOL_FABRIC_CATALOG_PATH="${VICUNA_OPENCLAW_TOOL_FABRIC_CATALOG_PATH:-/var/lib/vicuna/openclaw-catalog.json}"
export VICUNA_STATE_ROOT="${VICUNA_STATE_ROOT:-/var/lib/vicuna}"
export VICUNA_TELEGRAM_RUNTIME_TOOLS_SNAPSHOT_PATH="${VICUNA_TELEGRAM_RUNTIME_TOOLS_SNAPSHOT_PATH:-$VICUNA_STATE_ROOT/telegram-runtime-tools.json}"
export VICUNA_OPENCLAW_NODE_BIN="${VICUNA_OPENCLAW_NODE_BIN:-${TELEGRAM_BRIDGE_NODE_BIN:-}}"
export VICUNA_HOST_SHELL_ROOT="${VICUNA_HOST_SHELL_ROOT:-/home/vicuna/home}"
export VICUNA_HARD_MEMORY_DIR="${VICUNA_HARD_MEMORY_DIR:-$VICUNA_HOST_SHELL_ROOT/memories}"
export VICUNA_SKILLS_DIR="${VICUNA_SKILLS_DIR:-$VICUNA_HOST_SHELL_ROOT/skills}"
export VICUNA_DOCS_DIR="${VICUNA_DOCS_DIR:-$VICUNA_HOST_SHELL_ROOT/docs}"
export VICUNA_HEURISTIC_MEMORY_PATH="${VICUNA_HEURISTIC_MEMORY_PATH:-$VICUNA_HOST_SHELL_ROOT/heuristics/vicuna-heuristic-memory.json}"
export VICUNA_POLICY_DATASET_DIR="${VICUNA_POLICY_DATASET_DIR:-$VICUNA_STATE_ROOT/policy-datasets/nightly}"
export VICUNA_POLICY_REGISTRY_DIR="${VICUNA_POLICY_REGISTRY_DIR:-$VICUNA_STATE_ROOT/policy-registry}"
export VICUNA_POLICY_RUN_ROOT="${VICUNA_POLICY_RUN_ROOT:-$VICUNA_STATE_ROOT/policy-runs}"
export VICUNA_POLICY_MODEL_NAME="${VICUNA_POLICY_MODEL_NAME:-vicuna-governance}"
if [[ -z "${VICUNA_POLICY_PYTHON_BIN:-}" ]]; then
    if command -v python3.10 >/dev/null 2>&1; then
        export VICUNA_POLICY_PYTHON_BIN="$(command -v python3.10)"
    else
        export VICUNA_POLICY_PYTHON_BIN="$(command -v python3)"
    fi
fi
export VICUNA_POLICY_SERVER_URL="${VICUNA_POLICY_SERVER_URL:-http://127.0.0.1:${VICUNA_RUNTIME_PORT:-8080}}"
export VICUNA_POLICY_REGISTRY_HOST="${VICUNA_POLICY_REGISTRY_HOST:-127.0.0.1}"
export VICUNA_POLICY_REGISTRY_PORT="${VICUNA_POLICY_REGISTRY_PORT:-18081}"
export VICUNA_POLICY_DEFAULT_ALIAS="${VICUNA_POLICY_DEFAULT_ALIAS:-candidate}"
export VICUNA_POLICY_FALLBACK_ALIAS="${VICUNA_POLICY_FALLBACK_ALIAS:-champion}"
export VICUNA_POLICY_LIVE_ROLLOUT_RUNTIME_ENV_FILE="${VICUNA_POLICY_LIVE_ROLLOUT_RUNTIME_ENV_FILE:-$VICUNA_SYSTEM_ENV_FILE}"
export VICUNA_POLICY_LIVE_ROLLOUT_RUNTIME_SERVICE="${VICUNA_POLICY_LIVE_ROLLOUT_RUNTIME_SERVICE:-$VICUNA_RUNTIME_SERVICE_NAME}"
export VICUNA_POLICY_LIVE_ROLLOUT_STATE_PATH="${VICUNA_POLICY_LIVE_ROLLOUT_STATE_PATH:-$VICUNA_STATE_ROOT/policy-rollout/state.json}"
export VICUNA_POLICY_LIVE_ROLLOUT_JOURNAL_DIR="${VICUNA_POLICY_LIVE_ROLLOUT_JOURNAL_DIR:-$VICUNA_LOG_ROOT/policy-rollout/legacy-journal}"
export VICUNA_POLICY_SHADOW_MIN_REQUESTS="${VICUNA_POLICY_SHADOW_MIN_REQUESTS:-25}"
export VICUNA_POLICY_SHADOW_MAX_DISAGREEMENT_RATE="${VICUNA_POLICY_SHADOW_MAX_DISAGREEMENT_RATE:-0.25}"
export VICUNA_POLICY_SHADOW_MAX_CANDIDATE_FAILURE_RATE="${VICUNA_POLICY_SHADOW_MAX_CANDIDATE_FAILURE_RATE:-0.10}"
export VICUNA_RUNPOD_CAPTURE_SYNC_SERVICE_NAME="${VICUNA_RUNPOD_CAPTURE_SYNC_SERVICE_NAME:-vicuna-runpod-capture-sync.service}"
export VICUNA_RUNPOD_CAPTURE_SYNC_TIMER_NAME="${VICUNA_RUNPOD_CAPTURE_SYNC_TIMER_NAME:-vicuna-runpod-capture-sync.timer}"
export VICUNA_RUNPOD_CAPTURE_SYNC_HOST_DIR="${VICUNA_RUNPOD_CAPTURE_SYNC_HOST_DIR:-$VICUNA_STATE_ROOT/experimental-capture/live}"
export VICUNA_RUNPOD_CAPTURE_SYNC_REMOTE_DIR="${VICUNA_RUNPOD_CAPTURE_SYNC_REMOTE_DIR:-/workspace/llama-state-clean/capture}"
export VICUNA_RUNPOD_CAPTURE_SYNC_STATE_PATH="${VICUNA_RUNPOD_CAPTURE_SYNC_STATE_PATH:-$VICUNA_STATE_ROOT/runpod-capture-sync/state.json}"
export VICUNA_RUNPOD_CAPTURE_SYNC_LOCK_PATH="${VICUNA_RUNPOD_CAPTURE_SYNC_LOCK_PATH:-$VICUNA_STATE_ROOT/runpod-capture-sync/sync.lock}"
export VICUNA_RUNPOD_MISTRAL_RELAY_SERVICE_NAME="${VICUNA_RUNPOD_MISTRAL_RELAY_SERVICE_NAME:-vicuna-runpod-mistral-relay.service}"
export VICUNA_RUNPOD_MISTRAL_RELAY_HOST="${VICUNA_RUNPOD_MISTRAL_RELAY_HOST:-127.0.0.1}"
export VICUNA_RUNPOD_MISTRAL_RELAY_PORT="${VICUNA_RUNPOD_MISTRAL_RELAY_PORT:-18082}"
export VICUNA_RUNPOD_MISTRAL_RELAY_TIMEOUT_MS="${VICUNA_RUNPOD_MISTRAL_RELAY_TIMEOUT_MS:-1800000}"
export VICUNA_RUNPOD_MISTRAL_MODEL="${VICUNA_RUNPOD_MISTRAL_MODEL:-google/gemma-4-31B-it}"
export VICUNA_RUNPOD_MISTRAL_UPSTREAM_URL="${VICUNA_RUNPOD_MISTRAL_UPSTREAM_URL:-}"
export VICUNA_HOST_CAPTURE_RENDER_SERVICE_NAME="${VICUNA_HOST_CAPTURE_RENDER_SERVICE_NAME:-vicuna-host-capture-render.service}"
export VICUNA_HOST_CAPTURE_RENDER_TIMER_NAME="${VICUNA_HOST_CAPTURE_RENDER_TIMER_NAME:-vicuna-host-capture-render.timer}"
export VICUNA_HOST_CAPTURE_RENDER_SOURCE_PATH="${VICUNA_HOST_CAPTURE_RENDER_SOURCE_PATH:-$VICUNA_STATE_ROOT/experimental-capture/live/emotive_traces.jsonl}"
export VICUNA_HOST_CAPTURE_RENDER_VIDEO_DIR="${VICUNA_HOST_CAPTURE_RENDER_VIDEO_DIR:-$VICUNA_STATE_ROOT/experimental-capture/live/videos}"
export VICUNA_HOST_CAPTURE_RENDER_STATE_PATH="${VICUNA_HOST_CAPTURE_RENDER_STATE_PATH:-$VICUNA_STATE_ROOT/experimental-capture/render-state.json}"
export VICUNA_HOST_CAPTURE_RENDER_TIMEOUT_MS="${VICUNA_HOST_CAPTURE_RENDER_TIMEOUT_MS:-240000}"
